# Lsp Auto Compile_commands.json : compile_commands.json trough cmake CMakeLists.txt auto setup
# for lsp to work and index needed libraries
from sys import argv
from subprocess import run
from pathlib import Path


verbose = False
folder = '.'
if '-v' in argv: verbose = True; argv.remove('-v')
if '--verbose' in argv: verbose = True; argv.remove('--verbose')
if '-f' in argv: folder = argv[argv.index('-f')+1]; argv.remove(argv[argv.index('-f')+1]); argv.remove('-f')
if '--folder' in argv: folder = argv[argv.index('--folder')+1]; argv.remove(argv[argv.index('--folder')+1]); argv.remove('--folder')
if '-h' in argv or '--help' in argv:
    print( f'Usage:\n'+
            '    lspac [options] folder ...\n'+
            'Options:\n'+
            '    [--verbose] [-v] do not suppress commands output\n'+
            '    [--folder /some/path] [-f /some/path] set path where indexation will start (default is "./")\n'+
            '    [--help] [-h] show this help output\n'+
            'Examples:\n'+
            '    lspac C:/GLFW/include C:/GLAD/include\n'+
            '    lspac C:\\GLFW\\include --verbose "C:\\\\Users\\\\Acacia Door\\\\myincs"\n'+
            '    lspac C:/GLFW/include -f ..'+
            '    lspac -f /home/usr/myproj/cpp ~/libraries/SDL3/include'
          )
    exit()

pre = '\
# manual build command\n\
# cmake -S . -G "Unix Makefiles" -B cmake\n\
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)\n\
# .cpp files that affected (that folder and deeper)\n\
file(GLOB_RECURSE sources "${CMAKE_SOURCE_DIR}/*.cpp")\n\
add_executable(my_app ${sources})\n\
# .h files (autogenerated)\n\
set(includes\n\
'

aft = '\
)\n\
target_include_directories(my_app PUBLIC ${includes})\n\
'


f = open(f'{folder}/CMakeLists.txt', 'w')

f.write(pre)
for rawpath in argv[1:]:
    rawpath = Path(rawpath).as_posix()
    if rawpath[0]+rawpath[-1] != '""': libpath = '"'+rawpath+'"'
    else: libpath = rawpath
    f.write('  '+libpath+'\n')
f.write(aft)

f.close()


if not verbose:
    run(f'cmake -S {folder} -G "Unix Makefiles" -B {folder}/cmake > NUL 2>&1', shell=True)
    run(f'echo Y | copy {folder}\\cmake\\compile_commands.json {folder}\\compile_commands.json>NUL', shell=True)
else:
    run(f'cmake -S {folder} -G "Unix Makefiles" -B {folder}/cmake', shell=True)
    run(f'echo Y | copy {folder}\\cmake\\compile_commands.json {folder}\\compile_commands.json', shell=True)
